defaultPlacement: end
enableVersioning: true
handle: about
name: About
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  11ace5e4-2164-419f-aa8c-14a6ccb74727:
    enabledByDefault: true
    hasUrls: true
    template: about/_entry
    uriFormat: about
type: single
