dateModified: 1628364717
email:
  fromEmail: email@example.com
  fromName: 'Craft Plugin'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    4ceb2b2e-b080-410c-b994-4b6ac1e42c48: 'Main Nav' # Main Nav
    5c8bb9ac-158e-4511-adbd-e4ccddec2a6c: 'Fog Lamps' # Fog Lamps
    5d8c8721-d79f-4d33-a13f-89f1b65cff29: Wheels # Wheels
    22fb86f7-b3fe-4f11-b624-25c67fb9c682: 'Content Authors' # Content Authors
    535ddbac-f2c5-4e1f-8a30-051e3e68f19d: 'Product Admins' # Product Admins
    553c6b66-d999-458b-9b4d-d941cc28b6dd: 'Site Settings' # Site Settings
    791d4dc9-0bae-4126-b9cb-7718b2df18b6: Guide # Guide
    95304dab-45c1-409c-8633-fd625996c8d7: Headlights # Headlights
    bf477a41-bcac-4b0a-97ac-ab68423b4bf0: Products # Products
    e377ed68-cba4-4d8c-9ea4-44634bc5c8eb: 'Public Schema' # Public Schema
    eed46e7d-b369-4b50-841c-b785caf65b16: 'Drink Photos' # Drink Photos
plugins:
  guide:
    edition: pro
    enabled: true
    licenseKey: $PLUGIN_LICENSE_KEY
    schemaVersion: 3.0.0
    settings:
      assetVolume: 791d4dc9-0bae-4126-b9cb-7718b2df18b6 # Guide
      clientName: ''
      myCompanyName: ''
      templatePath: _guide
system:
  edition: pro
  live: true
  name: 'Craft Plugin'
  schemaVersion: 3.7.7
  timeZone: America/Los_Angeles
