dateModified: 1627780280
email:
  fromEmail: email@example.com
  fromName: 'Craft Plugin'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  guide:
    edition: pro
    enabled: true
    licenseKey: $PLUGIN_LICENSE_KEY
    schemaVersion: 3.0.0
    settings:
      assetVolume: 791d4dc9-0bae-4126-b9cb-7718b2df18b6
      clientName: ''
      myCompanyName: ''
      templatePath: _guide
system:
  edition: solo
  live: true
  name: 'Craft Plugin'
  schemaVersion: 3.7.7
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
