field: d65bd547-333e-464c-a99a-2badd5d23c4d # Content Tabs
fieldLayouts:
  5a1cefac-e7f6-4607-b1df-46f06eb656b7:
    tabs:
      -
        elements:
          -
            fieldUid: a8a7384d-21c3-4958-87a2-7076995cf447 # Custom Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a8a7384d-21c3-4958-87a2-7076995cf447: # Custom Text
    columnSuffix: cxgijuqh
    contentColumnType: text
    fieldGroup: null
    handle: customText
    instructions: ''
    name: 'Custom Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: specificationsTable
name: 'Specifications Table'
sortOrder: 2
