field: d65bd547-333e-464c-a99a-2badd5d23c4d # Content Tabs
fieldLayouts:
  cc6d96a4-b112-434c-9b10-77901d9a5a88:
    tabs:
      -
        elements:
          -
            fieldUid: 5629b286-3d10-4a84-9e90-098164c8f595 # Custom Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5629b286-3d10-4a84-9e90-098164c8f595: # Custom Text
    columnSuffix: axssiodi
    contentColumnType: text
    fieldGroup: null
    handle: customText
    instructions: ''
    name: 'Custom Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: videoTutorials
name: 'Video Tutorials'
sortOrder: 3
