defaultPlacement: end
fieldLayouts:
  b948b5cf-b0fc-484d-9e4e-2ff3e21ec46c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: plugTypes
name: 'Plug Types'
siteSettings:
  11ace5e4-2164-419f-aa8c-14a6ccb74727: # Craft Plugin
    hasUrls: true
    template: null
    uriFormat: 'plug-types/{slug}'
structure:
  maxLevels: null
  uid: 5b1213a6-8512-456b-9b45-3bfd447e2656
