fieldLayouts:
  e0aed0f3-c871-4afa-95b4-bc17e1cd05b0:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 211a41db-f9aa-4a81-8117-576cfd9cb3e1 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4c761429-91aa-474f-85b1-d9c5b6bfa0a0 # Product Overview
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: wbrowar\guide\fieldlayoutelements\GuideDisplay
            uiId: CQVhyeJRoFKGg5c
            width: 100
          -
            fieldUid: 5d7ab3e0-c350-472c-a7bd-7c6d899501e6 # Price
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 55a48e1a-738c-4fc4-b10b-d598fa7be858 # Model Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 5bc72bc2-802b-4a8d-bbae-e6f0f33035aa # Charging Level
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 9bd13089-c7ca-49c7-804b-018daf9c1c26 # Features List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            fieldUid: d65bd547-333e-464c-a99a-2badd5d23c4d # Content Tabs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: chargers
hasTitleField: true
name: Chargers
section: f7e1c238-5540-41fb-90d6-535844c622fb
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
